#!/usr/bin/env python3
"""Compose the Docker follow-up with an unchanged, clearly scoped historical cohort."""
import json,collections,pathlib
from analyze import ROOT
D=ROOT/'investigation';B=D/'natural-reading/containers'
def table(head,rows):
 return '| '+' | '.join(head)+' |\n| '+' | '.join(['---']*len(head))+' |\n'+''.join('| '+' | '.join(str(v).replace('|','\\|').replace('\n',' ') for v in r)+' |\n' for r in rows)+'\n'
def generate():
 rows=json.loads((B/'trial-results.json').read_text());tools=json.loads((B/'tool-results.json').read_text());active=[r for r in rows if r['debugging_began']]
 groups={c:[r for r in active if r['condition']==c] for c in ['default','conservative']}
 total=lambda g,k:sum(r.get(k) or 0 for r in g)
 pairs=[]
 for case in ['09','10']:
  for run in [1,2,3]:
   p=[next((r for r in groups[c] if r['case']==case and r['run']==run),None) for c in groups]
   if all(p):pairs.append(p)
 paired={c:[p[i] for p in pairs] for i,c in enumerate(groups)}
 low={c:total(g,'log_tokens_lower') for c,g in paired.items()};high={c:total(g,'log_tokens_upper') for c,g in paired.items()}
 reduction=(f"{100*(1-high['conservative']/low['default']):.1f}%–{100*(1-low['conservative']/high['default']):.1f}%" if low['default'] else 'not estimable')
 if all(low[c]==high[c] for c in groups) and low['default']:reduction=f"{100*(1-low['conservative']/low['default']):.1f}%"
 parts=[];a=parts.append
 a('# Natural log reading during agent debugging — Docker follow-up\n')
 a('This report now includes real-container cases 09–10 after Docker was enabled. The earlier natural-reading cohort and its Docker blocker are historical; its complete report is retained below and [separately](REPORT.natural-pre-containers.md). The [forced-full-read baseline](REPORT.full-read.md) remains a separate study. No earlier raw artifacts or analysis tables were overwritten.\n')
 a(f"## Current findings\n\nThe container follow-up has **{len(active)} active debugging trials** out of 12 planned slots. Across {len(pairs)} matched active pairs, returned log-inspection text totals **{low['default']:,}–{high['default']:,} reference tokens default** and **{low['conservative']:,}–{high['conservative']:,} conservative**, an observed reduction of **{reduction}**. Valid independent repairs: **{sum(r['fix_valid'] is True for r in groups['default'])}/{len(groups['default'])} default**, **{sum(r['fix_valid'] is True for r in groups['conservative'])}/{len(groups['conservative'])} conservative**.\n")
 a('The earlier non-container cohort observed 49.3% less returned log text and 8/11 valid repairs per condition. Cohorts are kept separate because Docker availability and collection dates differ. These small samples do not establish equivalence. Whole-session usage is separate from reference-tokenized log text, and its differences cannot all be attributed to logging.\n')
 a('Within matched completed pairs, case 09 consumed **5,920 default versus 6,066 conservative tokens (2.5% more)**: extra conservative searches/tails outweighed the shorter initial log. Case 10 consumed **13,485 versus 6,124 tokens (54.6% less)**. Each case had 2/2 valid repairs per arm in these matched pairs. The ninth active trial (case 09 default, repetition 3) was interrupted by quota after initial inspection, with no patch or recorded diagnosis; three slots never began. That unpaired observation is retained in active-trial totals but excluded from the matched text comparison. No completed trial showed a changed verified outcome; this does not establish equivalence.\n')
 a('## Container follow-up methods\n\nThe same failure fixtures and repair criteria are reused: case 09 must insert two distinct emails while retaining the PostgreSQL unique constraint and both records; case 10 must recognize the actual `worker ready` message. Docker Desktop 29.6.2 runs actual `postgres:17.6-alpine` and `alpine:3.22.1` containers. [Environment and image pulls](natural-reading/container-environment/) retain the exact probes/digests. [Four preflights](natural-reading/container-preflight/) confirmed both intended failures under both conditions; [four evaluator-only repair controls](natural-reading/container-controls/) test the original criteria independently. Controls are not agent trials.\n')
 a('Every trial starts in a fresh blind workspace with the same defective source/tests, complete failure.log, and identical instructions. Model `gpt-6-astra`, low reasoning, workspace-write sandbox, 120-second session budget, full Surefire, and alternating condition order match the earlier natural-reading cohort. Two trials can run concurrently. The conservative condition uses the Spring agent profile plus the existing case-06-only duplicate ownership property, which has no effect on these two cases. It does not enable aggressive Surefire trimming. Per-trial profile probes run separately before launch and their encoder artifact is excluded from measured failure.log.\n\nExact task:\n\n> This test fails. Diagnose the cause, make the smallest correct implementation change, and verify the fix. Complete test output is available in failure.log.\n\nThe identical workspace instructions and exact launch/test commands are retained per trial in `AGENTS.md`, `setup.json`, and `outcome.json`; [schedule](natural-reading/containers/schedule.json). No defect descriptions, reference repairs or earlier findings are copied into agent workspaces.\n')
 a('Container stdout and stderr are additionally available for voluntary discovery in `container-logs/`; they are retained as `initial-container-logs/` outside each workspace. Each stream is also preserved after agent reruns (where available) and independent verification. `.container.log` is an alternate combined copy: it must not be summed with separate STDOUT/STDERR copies as extra produced output. The primary endpoint counts whichever text an agent actually requests, including repeated copies if read. Setup target directories are removed before launch. Independent verification uses original tests/configuration in another pristine workspace and only the proposed implementation.\n')
 a('Docker is accessible to the outer evaluator, but agent test commands can encounter Docker socket permissions in the unchanged workspace-write sandbox. This is a limitation of agent-side verification, not evidence that Docker is unavailable or that a proposed patch is wrong. External real-container verification determines whether the implementation satisfies the unchanged tests. Each such blockage, attempted fallback, timeout and unresolved diagnosis remains visible in raw command returns.\n')
 a('The ordinary application suite also passed during this follow-up; [command and result](natural-reading/container-environment/ordinary-suite.json). The earlier approval-quota blocker described in the historical cohort was not a test failure and does not describe this new successful check.\n')
 a('## Container dispositions and per-trial results\n')
 a(table(['Status','Slots'],sorted(collections.Counter(r['status'] for r in rows).items())))
 a('Never-begun/quota-skipped slots are excluded from debugging outcome and text denominators. Once a quota error is observed the runner stops scheduling new trials; already-running sessions can finish. Missing provider usage remains unavailable.\n')
 a(table(['Case / arm / repeat','Log tokens lower–upper','Valid repair','Correct diagnosis','Seconds agent / verifier','Status'],[[f"{r['case']} / {r['condition']} / {r['run']}",f"{r['log_tokens_lower']:,}–{r['log_tokens_upper']:,}",r['fix_valid'],r['root_cause_correct'],f"{r['elapsed_seconds']:.1f} / {r['verification_seconds']:.1f}" if r['verification_seconds'] is not None else r['elapsed_seconds'],r['status']] for r in active]))
 a('Patch and diagnosis judgments are stored separately in [reviews.json](natural-reading/containers/reviews.json). A passing test does not excuse changed expectations, removed functionality or modified immutable files. Agent elapsed time and external verification time are separate; their sum is an observed time to independently verified repair for valid fixes only. The earlier timing caveat below remains applicable.\n')
 a('## Observed reading behavior and returned text\n\nClassification rules are the same as the historical methods below: log-directed reads count returned strings, repeated reads count again, test commands and source reads are separate, and mixed results retain their whole body plus identifiable literal log segments. Unallocated mixed results widen primary bounds. Filename discovery is not log consumption. All complete returned strings, offsets and commands are linked from [tool-results.json](natural-reading/containers/tool-results.json). Full-file counts below refer specifically to explicit `cat failure.log` requests; other observed commands must be interpreted from the ledger.\n')
 a(table(['Case / arm / repeat','Log calls','Searches','Exact repeats','Context requests','Full failure.log requests','Test reruns'],[[f"{r['case']} / {r['condition']} / {r['run']}"]+[r[k] for k in ['log_inspection_calls','search_calls','repeated_log_commands','context_requests','full_file_reads','test_reruns']] for r in active]))
 a(table(['Arm','Pure log tokens','Test-command tokens','Source-only tokens','Whole mixed tokens','Other tokens','Unallocated mixed calls'],[[c]+[total(g,k) for k in ['log_inspection_tokens','test_command_tokens','source_read_tokens','mixed_tokens','other_tokens','unallocated_mixed_calls']] for c,g in groups.items()]))
 a(f"Observed strategy totals: {total(active,'full_file_reads')} explicit full failure.log requests, {total(active,'search_calls')} log-content search commands, {total(active,'context_requests')} context/slice commands, and {total(active,'repeated_log_commands')} exact repeated log commands. Full reads are agent choices; searches of saved rerun output are also included. {total(active,'unallocated_mixed_calls')} mixed log results remain unallocated.\n")
 a('Mixed totals overlap attributed primary segments and must not be added to them. A fully redirected test followed solely by `tail` is classified mixed, but its whole returned body is attributed to the log tail because the test itself returns no console text. Ad hoc JShell checks count as test-command output; a Python command that reads source and asserts behavior counts as mixed source/test output. The classifier also distinguishes the word “find” inside a quoted search pattern from an actual find command. These rules have dedicated measurement checks; historical analysis files are not regenerated. Counts use tiktoken `o200k_base`, not an asserted exact tokenizer for Astra. Only returned text counts; stored container output is not automatically treated as consumed.\n')
 examples=[]
 for case in ['09','10']:
  for cond in groups:
   t=next((t for t in tools if t['case']==case and t['condition']==cond and t['log_directed']),None)
   if t:examples.append(t)
 for t in tools:
  if t['log_directed'] and ('rg ' in t['command'] or 'tail ' in t['command']) and t not in examples:
   examples.append(t)
   if len(examples)>=7:break
 for t in examples:
  p=ROOT/t['returned_text'];ls=p.read_text().splitlines();idx=next((i for i,s in enumerate(ls) if 'duplicate key' in s or 'Timed out waiting' in s),0)
  a(f"Case {t['case']}, {t['condition']}, repetition {t['run']}:\n\n```sh\n{t['command']}\n```\n\n[Complete returned body]({p.relative_to(D)}) ({t['category']}; {t['log_token_lower']}–{t['log_token_upper']} attributed tokens). Representative excerpt:\n\n```text\n"+'\n'.join(ls[max(0,idx-2):idx+8])+'\n```\n')
 a('## Container actual session usage\n')
 a(table(['Case / arm / repeat','Input','Cached input','Output'],[[f"{r['case']} / {r['condition']} / {r['run']}"]+[r[k] if r[k] is not None else 'unavailable' for k in ['input_tokens','cached_input_tokens','output_tokens']] for r in active]))
 a('Provider-reported input includes cached input. These are whole-session values, affected by source reads, test execution, repeated context, instructions and cache state. They are not interchangeable with cumulative reference-tokenized log returns.\n')
 a('## Container secondary evidence and limitations\n\n[Secondary complete-file and predetermined extractions](natural-reading/containers/secondary-results.csv) are retained separately from the primary reading endpoint. Legacy extraction windows/markers were designed around fixture/Surefire boundaries and may omit Testcontainers diagnostics emitted before those markers. Low extraction counts alone do not demonstrate diagnostic adequacy. Separate stream sizes/counts and immutable-evidence checks are in [verification.json](natural-reading/containers/verification.json).\n\nThis is a small fixture study with constrained editable source and a single model/budget. Sandbox Docker restrictions limit agent-side verification. No claim of equivalent debugging ability follows from equal observed success counts. Resource errors are distinguished from active debugging failures. Cohort totals are not pooled to conceal different conditions or missing trials. All nine active agents chose one full initial read; none read the separately stored container stream files. Two rg searches and three tails inspected saved test-rerun output, not selective slices of the original failure.log. Conservative PostgreSQL sessions wrote and reread their own /tmp log files despite the workspace-only instruction; observed other-arm commands did not use these filenames, and the two conservative sessions ran sequentially. This is a procedural-isolation deviation, not proof of adversarial isolation. Returned text remains recorded, but those temporary files are not part of the retained raw filesystem. The exact patch reviews, unavailable usage and ambiguous text attribution govern interpretation.\n')
 a('## Reproduction and evidence\n\n```sh\npython3 investigation/scripts/natural_trials.py --batch NEW_CONTAINER_BATCH --cases 09,10 --repeats 3 --workers 2 --seconds 120\nTIKTOKEN_CACHE_DIR="$PWD/investigation/.tokenizer-cache" investigation/.venv/bin/python investigation/scripts/natural_analyze.py --batch NEW_CONTAINER_BATCH\n```\n\nUse a new batch name; the harness refuses overwrite. [Raw trials](natural-reading/containers/trials/), [trial table](natural-reading/containers/trial-results.csv), [raw manifest](natural-reading/containers/raw-manifest.json), [pre-container preservation manifest](natural-reading/pre-container-snapshot/preserved-sha256.json). Run `container_report.py` to compose this report after analysis and review; it reads the preserved historical report and never regenerates historical tables or plots.\n')
 a('---\n\n# Historical natural-reading cohort: cases 01–08\n\n**Scope of everything below:** the earlier non-container collection. Statements that Docker was unavailable, counts of 22 trials, all-full-read behavior, and its conclusions refer only to that earlier cohort. They are not current Docker status or container follow-up results. The text is reproduced unchanged from the preserved pre-container report.\n')
 a((D/'REPORT.natural-pre-containers.md').read_text())
 (D/'REPORT.md').write_text('\n'.join(parts))
if __name__=='__main__':generate()
