#!/usr/bin/env python3
"""Generate the revised report solely from natural-reading evidence."""
import collections,json,os,pathlib,statistics,textwrap
from analyze import ROOT
from natural_trials import PROMPT,GUARD
# Keep historical tables/plots immutable once the container follow-up exists.
if (ROOT/'investigation/natural-reading/containers/trial-results.json').exists():
 from container_report import generate
 generate()
 raise SystemExit(0)
D=ROOT/'investigation';B=D/'natural-reading/main'
rows=json.loads((B/'trial-results.json').read_text());tools=json.loads((B/'tool-results.json').read_text());secondary=json.loads((B/'secondary-results.json').read_text())
active=[r for r in rows if r['debugging_began']]
cases=json.loads((D/'cases.json').read_text())
conds=['default','conservative']
def tbl(headers,data):return '| '+' | '.join(headers)+' |\n| '+' | '.join(['---']*len(headers))+' |\n'+''.join('| '+' | '.join(str(v).replace('|','\\|').replace('\n',' ') for v in row)+' |\n' for row in data)+'\n'
def select(case,cond):return [r for r in active if r['case']==case and r['condition']==cond]
def fmt(group,key):
 vals=[r[key] for r in group if r.get(key) is not None]
 if not vals:return '—'
 return f'{statistics.mean(vals):,.1f} [{min(vals):,}–{max(vals):,}]'
def sumkey(group,key):return sum(r.get(key) or 0 for r in group)
pairs=[]
for case in cases:
 for run in [1,2,3]:
  p=[next((r for r in active if r['case']==case and r['run']==run and r['condition']==cond),None) for cond in conds]
  if all(p):pairs.append(p)
paired={c:[p[i] for p in pairs] for i,c in enumerate(conds)}
usagepairs=[p for p in pairs if all(r['input_tokens'] is not None for r in p)]
status=collections.Counter(r['status'] for r in rows)
lower={c:sumkey(paired[c],'log_tokens_lower') for c in conds};upper={c:sumkey(paired[c],'log_tokens_upper') for c in conds}
if lower['default']:
 reduction_lo=100*(1-upper['conservative']/lower['default']);reduction_hi=100*(1-lower['conservative']/upper['default'])
 reduction=f'{reduction_lo:.1f}%' if abs(reduction_lo-reduction_hi)<.01 else f'{reduction_lo:.1f}%–{reduction_hi:.1f}%'
else:reduction='not estimable'
success={c:sum(r['fix_valid'] is True for r in active if r['condition']==c) for c in conds}
ns={c:sum(r['condition']==c for r in active) for c in conds}
quota=sum(n for s,n in status.items() if 'quota' in s)
parts=[];a=parts.append
a('# Natural log reading during agent debugging\n\nRevised investigation, October 2026. The unit of measurement is text returned by an agent’s chosen inspections, not a log file merely stored on disk.\n')
a('## Abstract\n')
a(f'''We compared default logging with the final conservative configuration (Spring `agent` profile, case-specific duplicate exception ownership, and full Surefire reports). Both conditions received the same neutral task and could choose any reading strategy. The main schedule planned 48 trials across eight available failure cases, three per condition. At report generation, **{len(active)} trials performed debugging**, with {quota} quota-related outcomes. Docker’s unavailable daemon prevented cases 09–10. A separate two-trial harness pilot is retained and excluded from main results.\n\nAcross **{len(pairs)} matched active trial pairs**, cumulative identifiable log-inspection text was {lower['default']:,}–{upper['default']:,} reference tokens for default and {lower['conservative']:,}–{upper['conservative']:,} for conservative, an observed reduction of **{reduction}**. Bounds reflect any inseparable mixed output. These are exact `o200k_base` counts of recorded returned text, not exact Astra model token attribution. Valid independently verified fixes were **{success['default']}/{ns['default']} default and {success['conservative']}/{ns['conservative']} conservative**. These are small, resource- and time-limited observations, not evidence of equivalence. Whole-session usage is reported separately. Prior forced-first-full-read trials are preserved as a different baseline and are not pooled with this study.\n''')
a('## 1. Research questions and baseline separation\n\nRQ1: Does the conservative profile reduce cumulative text actually returned during agents’ self-selected log inspections, including repeated reads? RQ2: Do verified debugging outcomes differ? Full reads are allowed and may be an observed strategy; the experiment does not assume an agent will use grep. The primary endpoint excludes test execution and source reading unless an identifiable log segment is recovered from mixed output.\n\nThe [previous full-read report](REPORT.full-read.md), [previous instructions](README.full-read.md), and original `raw/`, `trials/`, `extracted/`, result tables and positive controls remain unchanged. Their hashes are recorded in [the baseline manifest](baselines/full-read/preserved-sha256.json). That earlier study used an aggressive P4-trimmed treatment and asked agents to start with a complete file read. It is a separate intervention, not a control arm for this revision. No old percentages or sessions enter the new primary totals.\n')
a('## 2. Methods and exact task\n')
a('### 2.1 Model, task and constraints\n\nEvery new session receives exactly:\n\n> '+PROMPT+'\n\nThe same [workspace instructions](natural-reading/main/trials/01/default/1/AGENTS.md) identify `./test.sh` and the editable implementation file, forbid changes to expectations/tests/configuration or disabling functionality, and prohibit reading evaluation data outside the workspace. They do not prescribe log reads or mention token savings. The exact prompt and instructions are stored per trial.\n\nModel `gpt-6-astra`, low reasoning effort, Codex CLI 0.154.0-alpha.6.2, fresh ephemeral sessions, workspace-write sandbox and 120-second session wall budget are fixed across conditions. Two separate workspaces may execute concurrently. The launch schedule alternates condition order by case and repetition; concurrency means completion order can differ. [Schedule and prompt](natural-reading/main/schedule.json). No session resumes or informed evaluator sessions serve as blind trials.\n')
a('### 2.2 Configuration and profile verification\n\nBoth conditions use Java 25, Spring Boot 4.1.1, Maven 3.9.16, Kotlin 2.3.21 and Surefire 3.5.6. Normal application behavior and fixtures are unchanged. Both explicitly set `-DtrimStackTrace=false`; neither enables `agent-reports`. The conservative condition additionally sets `-Dspring.profiles.active=agent -Dexperiment.deduplicate=true`. The latter only changes duplicate exception ownership in caught-database case 06, as in the prior conservative definition; ERROR events remain. The Spring profile itself remains unchanged:\n\n```yaml\n'+(ROOT/'src/main/resources/application-agent.yml').read_text()+'```\n')
a('Before **each** trial, a separate Maven invocation runs `ProfileVerificationTest`. It asserts the requested/active profile match, inspects the actual Logback console encoder and writes `profile-verification.txt` outside the agent workspace. Probe stdout/stderr are separate artifacts. It also probes the unit-only case, while recognizing that the unit failure itself does not start Spring. `FailureCasesTest` no longer prints the effective regex. The measured failure log retains normal Spring startup output, including its ordinary active-profile announcement, but no custom pattern dump. [Example verified encoder](natural-reading/main/trials/02/conservative/1/profile-verification.txt).\n\nThe Kotlin compiler daemon is disabled identically to avoid the earlier known daemon-directory blocker. This environmental improvement and changed instrumentation further prevent causal comparisons with the old baseline. Network/loopback restrictions inside the agent sandbox remain a possible source of verification friction; the external verifier runs where controlled component tests can execute.\n')
a('### 2.3 Isolation and independent verification\n\nEach external temporary workspace receives only source, POM, test fixtures/resources, neutral instructions, test.sh and the complete initial `failure.log`. It receives no case manifest, reference repair, report, previous findings or trial artifacts. The evaluator verifies the intended initial failure and profile before launching the agent; failed setup is not a debugging trial. Setup’s target directory is removed before agent activity, so there are no probe reports or stale compiled repairs. `failure.log` concatenates complete stdout then stderr without truncation and without asserting inter-stream ordering.\n\nA second pristine directory independently verifies the proposed `Defects.java` using the original tests and build command. It never trusts the agent’s scripts, target/classes or edited expectations. Immutable changes are recorded, patches and diagnoses are reviewed, and valid fixes must preserve intended functionality. Independent XML/text test reports, stdout/stderr, patches and source are retained. Setup’s generated report files are not separately retained beyond complete console output. Every process has a bounded timeout; temporary workspaces are cleaned up. Isolation is procedural/workspace-based, not an adversarial barrier against ignoring outside-read instructions.\n')
a('### 2.4 Cases and repair criteria\n')
a(tbl(['Case','Failure fixture','Verified criterion'],[[c,v['name'],v['criterion']] for c,v in cases.items()]))
a('Criteria are reused from [cases.json](cases.json) and the original tests. The nested port and startup cases require 8080. Database tests require two distinct stored emails, not dropped constraints or skipped inserts. The HTTP fixture is intentionally retained as the original two-stage problem: correcting `/wrong` to `/price` can expose `UnknownContentTypeException`; a route-only patch is incomplete. Asynchronous repairs must retain execution and propagation behavior. Reference repairs remain outside agent workspaces.\n\n`docker info` still cannot reach the Docker Desktop daemon. Therefore cases 09–10 have no natural-reading trials, no synthetic container output and no zero-valued savings. [Exact blocker](natural-reading/environment/docker.stderr). The same real Testcontainers fixtures and bounded cleanup remain available in the reproduction protocol.\n')
a('## 3. Measurement and classification\n\nThe primary measure is the cumulative `o200k_base` count of **returned log-inspection strings**, including repetitions. A file stored on disk is not automatically counted. Completed Codex command events supply `aggregated_output`; every original returned body is saved under each trial’s `returned-text/`, along with recovered log segments and character offsets. This measures the CLI-visible body, not hidden model protocol framing. The tokenizer is tiktoken 0.14.0; its installed mapping cannot establish exact `gpt-6-astra` log tokens. Actual model-reported session input, cached input and output are separate measurements.\n')
a(tbl(['Class','Rule'],[['Log inspection','Content reads/searches aimed at failure.log, a log file or Surefire reports; include line numbers/context formatting and repeated reads. Filename-only discovery is not a read.'],['Test command','Invoking ./test.sh or Maven; count all returned test output separately, even when it contains logging.'],['Source read','Reading code, tests, build scripts or instructions without logs, test execution, discovery or status output in that result.'],['Mixed','Combined log/source/test/discovery commands. Retain the complete body separately; recover only literal known full-log or numbered slice matches for primary attribution.'],['Other','Discovery, repository status and other command output.']]))
a('For mixed results, `cat failure.log`, simple numbered `sed`, `head` and `tail` can be attributed only when their exact expected text appears in the actual returned body. Repeated occurrences at different positions count repeatedly. No missing/truncated text is filled from the disk file. Unresolved log-containing mixed results contribute zero to the primary lower bound and the entire mixed body to the upper bound. Entire mixed-result counts are an overlapping diagnostic view and must not be added to recovered log tokens again. Segment token counts are computed independently; tokenization across different boundaries is not exactly additive.\n\nCounters distinguish content searches, exact repeated command strings, context/slice requests, full-file cat requests and test reruns. A full-file request may be tool-truncated; only returned strings count. Context requests are not automatically claimed to be successful context expansion. All 107 completed command results were audited: 13 other, 34 mixed, 30 test-command-only, 11 log-only and 19 source-only bodies. Eleven mixed bodies contained exactly recoverable full-log segments, giving 22 observed log reads overall; none was unallocated or marked truncated. [Classification audit](natural-reading/main/classification-audit.json). The classifier’s shell-pattern rules are in [natural_analyze.py](scripts/natural_analyze.py); measurement unit checks are in [test_natural_analyze.py](scripts/test_natural_analyze.py). The full [protocol](natural-reading/PROTOCOL.md) specifies boundaries, limitations and reproduction.\n')
a('## 4. Natural-reading results\n')
a('### 4.1 Trial disposition\n')
a(tbl(['Recorded state','Slots'],sorted(status.items())))
a('“Not scheduled” and “model never began” do not enter active-trial success or token denominators. Quota-interrupted sessions that already used debugging tools remain active observations, with incomplete usage explicitly missing. Timeouts after genuine activity are unresolved debugging outcomes, not skipped trials. Planned three-repetition slots must not be confused with completed independent sessions. The runner stops scheduling new debugging work after a quota error; already-running sessions can finish.\n')
a(tbl(['Case','Default active n','Conservative active n','Default valid fixes','Conservative valid fixes','Diagnosis recorded correct D/C'],[[c,len(select(c,'default')),len(select(c,'conservative')),f"{sum(r['fix_valid'] is True for r in select(c,'default'))}/{len(select(c,'default'))}" if select(c,'default') else 'unobserved',f"{sum(r['fix_valid'] is True for r in select(c,'conservative'))}/{len(select(c,'conservative'))}" if select(c,'conservative') else 'unobserved',str(sum(r['root_cause_correct'] is True for r in select(c,'default')))+' / '+str(sum(r['root_cause_correct'] is True for r in select(c,'conservative')))] for c in cases]))
a('Eight of eleven active trials per condition produced valid fixes. The unresolved cases were startup case 04 repetition 1 and MVC case 03 repetition 2 (timeouts without a patch), and HTTP case 07 repetition 1 (route-only patch, followed by UnknownContentTypeException in external verification). Both HTTP agents reported loopback socket permission failures during their own test run. No changed expectations, deleted tests or functionality-disabling repairs were accepted. Correct-diagnosis counts require recorded evidence in the explanation or explicit diagnosis, not inference solely from having read a stack trace. Missing explanations remain unknown. A passing external test does not override an invalid patch or altered expectations. Review details and unresolved causes are recorded per outcome; [main trial evidence](natural-reading/main/trials/).\n')
a('### 4.2 Primary returned-log text\n\nMean [minimum–maximum] across active trials. Lower/upper bounds coincide when every mixed log portion is attributable. Missing cases are not assigned zero.\n')
a(tbl(['Case','Default log tokens, lower','Default upper','Conservative lower','Conservative upper'],[[c]+[fmt(select(c,cond),key) for cond in conds for key in ['log_tokens_lower','log_tokens_upper']] for c in cases]))
a(f'For the {len(pairs)} matched active case/repetition pairs, sum default lower/upper = **{lower["default"]:,}/{upper["default"]:,}**, conservative = **{lower["conservative"]:,}/{upper["conservative"]:,}**. The bounded reduction is **{reduction}**, calculated conservatively as `1 − conservative_upper/default_lower` through `1 − conservative_lower/default_upper`. This weights longer observed inspections more heavily; it is not a universal percentage or an unweighted average of per-case savings. Unpaired sessions remain in per-case tables but are excluded from this pooled comparison.\n')
a(f"The corresponding identifiable returned-log text totals are {sumkey(paired['default'],'log_bytes_lower'):,} bytes default and {sumkey(paired['conservative'],'log_bytes_lower'):,} bytes conservative. This demonstrates reduced returned text independently of whether the reference tokenizer matches Astra.\n")
a('![Returned log text](natural-reading/main/plots/returned-log-tokens.png)\n')
a('### 4.3 Observed reading strategies and separate output classes\n')
a(tbl(['Case / condition','Log inspections','Search commands','Exact repeats','Context requests','Full-file requests','Test reruns'],[[c+' / '+cond]+[sumkey(select(c,cond),k) for k in ['log_inspection_calls','search_calls','repeated_log_commands','context_requests','full_file_reads','test_reruns']] for c in list(cases)[:8] for cond in conds if select(c,cond)]))
a(tbl(['Condition','Pure log result tokens','Test-command tokens','Source-only tokens','Whole mixed-result tokens','Other tokens','Unallocated mixed calls'],[[cond]+[sumkey([r for r in active if r['condition']==cond],k) for k in ['log_inspection_tokens','test_command_tokens','source_read_tokens','mixed_tokens','other_tokens','unallocated_mixed_calls']] for cond in conds]))
a('These output-class totals describe all active sessions, including unpaired ones. Whole mixed results include source or other text and overlap recovered primary log segments; they are shown separately rather than mislabeled as logs. Test reruns can produce large output even when the initial inspection is short. In this completed sample all 22 active sessions chose one full-file read, with no repeated log inspections or log-content searches/context expansions. Therefore the primary endpoint happens to match one returned full-log body per trial; that is an observed choice, not an assumed reading policy. Source-code rg searches and filename discovery did occur and are classified separately. The number of full-file reads is an empirical result: choosing `cat` is permitted, and the revised prompt does not force a search strategy. Raw commands and body paths are in [tool-results.csv](natural-reading/main/tool-results.csv).\n')
a('### 4.4 Strategies and representative returned excerpts\n\nThese are bounded illustrations from recorded tool returns, not replacements for the full saved strings used in measurement.\n')
examples=[]
for predicate in [lambda t:t['log_directed'] and ('rg ' in t['command'] or 'grep ' in t['command']) and '--files' not in t['command'],lambda t:t['log_directed'] and ('sed ' in t['command'] or 'tail ' in t['command']),lambda t:t['category']=='mixed' and t['segments'],lambda t:t['category']=='log_inspection']:
 t=next((t for t in tools if predicate(t) and t not in examples),None)
 if t:examples.append(t)
for condition in ['default','conservative']:
 t=next((t for t in tools if t['case']=='02' and t['condition']==condition and t['run']==1 and t['log_directed']),None)
 if t and t not in examples:examples.append(t)
for t in examples:
 path=ROOT/t['returned_text'];s=path.read_text();rel=path.relative_to(D)
 lines=s.splitlines();start=next((i for i,line in enumerate(lines) if 'ERROR' in line),0);excerpt=lines[start:start+14]
 a(f'**Case {t["case"]}, {t["condition"]}, repetition {t["run"]}, result {t["index"]}** — {t["category"]}; primary log attribution {t["log_token_lower"]}–{t["log_token_upper"]} reference tokens.\n\n```sh\n{t["command"]}\n```\n\n[Complete returned body]({rel})\n\n```text\n'+ '\n'.join(excerpt)+'\n```\n')
if not any(r['search_calls'] for r in active):a('No completed log-content grep/rg/awk commands were observed in this main sample. Filename discovery does not count as log-content search. Do not invent search-strategy examples where the agent instead chose full reads.\n')
a('## 5. Actual session usage, time and verified outcomes\n')
a(tbl(['Case / condition / repeat','Session input','Cached input','Output','Session seconds','External verification seconds','Valid fix','Status'],[[r['case']+' / '+r['condition']+' / '+str(r['run']),r['input_tokens'] if r['input_tokens'] is not None else 'unavailable',r['cached_input_tokens'] if r['cached_input_tokens'] is not None else 'unavailable',r['output_tokens'] if r['output_tokens'] is not None else 'unavailable',f"{r['elapsed_seconds']:.1f}",f"{r['verification_seconds']:.1f}" if r['verification_seconds'] is not None else '—',r['fix_valid'],r['status']] for r in active]))
if usagepairs:
 u={c:[p[i] for p in usagepairs] for i,c in enumerate(conds)}
 a(f'Actual usage is complete for **{len(usagepairs)} matched pairs**. Input totals: {sumkey(u["default"],"input_tokens"):,} default and {sumkey(u["conservative"],"input_tokens"):,} conservative; cached input: {sumkey(u["default"],"cached_input_tokens"):,} and {sumkey(u["conservative"],"cached_input_tokens"):,}; output: {sumkey(u["default"],"output_tokens"):,} and {sumkey(u["conservative"],"output_tokens"):,}. These are provider-reported whole-session values, not the reference-tokenized log endpoint. Cached input is included in input, not added to it. Instructions, source reads, repeated context, cache state, test runs and tool overhead can explain session differences; no attribution of all session differences to logging is made.\n')
else:a('No matched pair has complete provider usage. No session-token saving is estimated.\n')
a('Elapsed session time is the Python monotonic duration recorded by the harness, including reasoning/tool activity but not initial setup; independent verification duration is separate. For valid fixes their sum is an observable time to external verification, not the exact moment the agent discovered the repair. Unresolved/time-limited trials have no successful time-to-fix. The planned 120-second subprocess timeout is the same in each condition. Some timed-out session stderr calendar timestamps span substantially longer than the recorded monotonic duration; the cause is not established (host suspension is one possible explanation). Both original timestamps and measured durations are retained; do not treat these timings as reliable uninterrupted calendar wall times. No retry/resume is silently counted as an independent trial.\n\n![Verified outcomes](natural-reading/main/plots/outcomes.png)\n')
a('## 6. Secondary complete-file and fixed-extraction comparisons\n\nThese counts describe available text and predetermined selections, **not** actual agent input unless a recorded read returned them. The same legacy marker/window/boundary/dedup rules are applied to instrument-free initial logs. Means below use generated logs from active sessions; repetitions and case availability differ with resource limits.\n')
a(tbl(['Case / condition','Complete file','20-line window','Filtered 40','Boundary','Dedup'],[[c+' / '+cond]+[fmt([s for s in secondary if s['case']==c and s['condition']==cond and s['method']==m and any(r['case']==c and r['condition']==cond and r['run']==s['run'] for r in active)],'tokens') for m in ['complete','window20','filtered40','boundary','dedup']] for c in list(cases)[:8] for cond in conds if select(c,cond)]))
a('Secondary full-file savings are not substituted for the cumulative observed-reading comparison. Fixed windows may omit nested causes even when their token count is low; the prior diagnostic investigation remains relevant as a content warning, not new performance evidence. [Secondary CSV](natural-reading/main/secondary-results.csv).\n')
a('## 7. Limitations and interpretation\n\nThe final ordinary-suite rerun was not executed: automatic approval review rejected the requested command because its reviewer hit the account usage limit. This is separate from the captured per-trial independent verification. The prior ordinary-suite successes belong to the baseline and are not represented as new checks.\n\n- No log-content search or context-expansion strategy was observed, so this study does not establish savings for selective grep/rg workflows. The model chooses its strategy freely but still operates on small injected fixtures with an identified editable implementation file. Generalization to large repositories or other agents is untested.\n- Only eight cases can run here; real container failure and readiness diagnostics remain untested with Docker stopped.\n- Three repetitions were planned; actual counts above, quota states and timeouts determine the evidence. A small sample with equal successes cannot establish equivalence or non-inferiority.\n- CLI output captures visible command bodies, not every hidden serialized model-input field. Exact Astra log-token attribution is unavailable; o200k_base is a reference tokenizer.\n- Mixed-output attribution is deliberately conservative. Ambiguous bodies widen bounds; full-read requests do not imply an entire file reached the model when tool truncation occurred.\n- Shell command classification has finite recognized forms and requires auditing. Filesystem discovery is not a content read; test output is not silently pooled with inspections.\n- Sandbox restrictions, concurrent execution, cache state, backend interruptions and wall budgets can affect success/time/usage independently of formatting. Source/test expectations and model settings are held constant, but all such external conditions cannot be randomized away.\n- The conservative treatment includes narrowly scoped duplicate ownership for case 06; its contribution is not separable from prefix/trace formatting in this two-condition study.\n- This revision improves instrumentation and disables the Kotlin compiler daemon in both arms. It is not a causal before/after comparison against the old full-read/P4 study.\n')
a('## 8. Conclusions limited to these observations\n')
a(f'In the {len(pairs)} matched active pairs, the conservative configuration changed cumulative identifiable returned log-inspection text by a **{reduction} reduction**, with ambiguity represented in the bounds rather than filled from files on disk. Agents were free to choose full reads, searches and context requests; the strategy counts show what they actually did. Verified valid fixes were **{success["default"]}/{ns["default"]} default versus {success["conservative"]}/{ns["conservative"]} conservative**. Interpret those counts alongside the case/repetition table, not as evidence that debugging ability is unchanged. Cases or repetitions prevented by quota or Docker remain untested. Whole-session token differences are separate observations and cannot be assigned wholly to logging.\n')
a('## Appendix: commands, evidence and reproducibility\n\n```sh\npython3 investigation/scripts/natural_trials.py --batch NEW_BATCH --repeats 3 --workers 2 --seconds 120\ninvestigation/.venv/bin/python investigation/scripts/natural_analyze.py --batch NEW_BATCH\ninvestigation/.venv/bin/python investigation/scripts/test_natural_analyze.py\n```\n\nUse fresh batch names; the runner refuses overwrite. The report generator currently summarizes `main`, making the evidence selection explicit. Per-trial `setup.json` records exact probe and initial test commands, source/test/log hashes and failure identities; `outcome.json` records actual CLI command, verification command, elapsed times and provider usage. [Integrity checks](natural-reading/verification.json) confirm identical initial implementation/test hashes across all 22 active trials, instrument-free complete captures, 22 independent test reports, and 3,663 unchanged baseline artifacts. [Raw artifact hashes](natural-reading/main/raw-manifest.json) cover original new evidence. [Manual patch and diagnosis reviews](natural-reading/main/reviews.json) remain separate from raw outcomes.\n\n[Full protocol](natural-reading/PROTOCOL.md), [source manifest](natural-reading/manifest.json), [machine-readable trial results](natural-reading/main/trial-results.json), [tool results](natural-reading/main/tool-results.json), [all main trials](natural-reading/main/trials/), [excluded pilot](natural-reading/pilot/).\n\nSupporting configuration documentation remains the [Spring Boot logging reference](https://docs.spring.io/spring-boot/reference/features/logging.html), [Logback layouts](https://logback.qos.ch/manual/layouts.html), [Surefire parameters](https://maven.apache.org/surefire/maven-surefire-plugin/test-mojo.html) and the locally verified Codex CLI. No new price claim is made.\n')
(D/'REPORT.md').write_text('\n'.join(parts))
os.environ.setdefault('MPLCONFIGDIR',str(D/'.mpl'))
import matplotlib;matplotlib.use('Agg')
import matplotlib.pyplot as plt
import numpy as np
(B/'plots').mkdir(exist_ok=True)
fig,ax=plt.subplots(figsize=(10,4.5));x=np.arange(8)
for offset,cond in [(-.18,'default'),(.18,'conservative')]:
 vals=[statistics.mean(r['log_tokens_lower'] for r in select(c,cond)) if select(c,cond) else float('nan') for c in list(cases)[:8]]
 errors=[statistics.mean(r['log_tokens_upper']-r['log_tokens_lower'] for r in select(c,cond)) if select(c,cond) else 0 for c in list(cases)[:8]]
 ax.bar(x+offset,vals,.36,label=cond,yerr=[np.zeros(8),errors],capsize=3)
ax.set_xticks(x,list(cases)[:8]);ax.set_xlabel('Case; per-arm n shown in report');ax.set_ylabel('Mean cumulative returned log reference tokens');ax.set_title('Natural reading: o200k_base, ambiguity bounds if present');ax.legend();fig.tight_layout();fig.savefig(B/'plots/returned-log-tokens.png',dpi=160);plt.close(fig)
fig,ax=plt.subplots(figsize=(10,4.5))
for offset,cond in [(-.18,'default'),(.18,'conservative')]:
 vals=[sum(r['fix_valid'] is True for r in select(c,cond))/len(select(c,cond)) if select(c,cond) else float('nan') for c in list(cases)[:8]]
 ax.bar(x+offset,vals,.36,label=cond)
 for i,c in enumerate(list(cases)[:8]):
  if select(c,cond):ax.text(i+offset,(vals[i] or 0)+.025,f"{sum(r['fix_valid'] is True for r in select(c,cond))}/{len(select(c,cond))}",ha='center',fontsize=8)
ax.set_xticks(x,list(cases)[:8]);ax.set_ylim(0,1.2);ax.set_xlabel('Case');ax.set_ylabel('Observed valid-fix fraction');ax.set_title('Independent verification; small sample, no equivalence claim');ax.legend(loc='upper right');fig.tight_layout();fig.savefig(B/'plots/outcomes.png',dpi=160);plt.close(fig)
print('Revised REPORT.md generated from',len(active),'active trials')
