#!/usr/bin/env python3
import json,statistics,pathlib,os,collections,textwrap
from analyze import ROOT
D=ROOT/'investigation'
rows=json.loads((D/'results-v2.json').read_text())+json.loads((D/'results-conservative-v2.json').read_text())
trials=json.loads((D/'trial-results-v1.json').read_text())+json.loads((D/'trial-results-supplemental.json').read_text())
active=[r for r in trials if r['patch_present']]
cases=json.loads((D/'cases.json').read_text())
def group(case,config,method='complete'):
 return [r for r in rows if r['case']==case and r['config']==config and r['method']==method]
def mean(rs,key='tokens'):return statistics.mean(r[key] for r in rs)
def form(rs,key='tokens'):
 vals=[r[key] for r in rs];return f'{statistics.mean(vals):,.1f} [{min(vals):,}–{max(vals):,}]'
def table(headers,lines):
 return '| '+' | '.join(headers)+' |\n| '+' | '.join(['---']*len(headers))+' |\n'+''.join('| '+' | '.join(map(str,line))+' |\n' for line in lines)+'\n'
def reduction(config):
 default=sum(r['tokens'] for r in rows if r['config']=='default' and r['method']=='complete')
 treatment=sum(r['tokens'] for r in rows if r['config']==config and r['method']=='complete')
 return 100*(1-treatment/default)
paired=[c for c in cases if all(any(r['case']==c and r['config']==cfg and r['input_tokens'] is not None for r in active) for cfg in ['default','agent'])]
def selected(config):return [r for r in active if r['config']==config and r['case'] in paired]
def total(config,key):return sum(r[key] for r in selected(config))
log_reduction=100*(1-sum(r['log_related_o200k_tokens'] for r in active if r['config']=='agent')/sum(r['log_related_o200k_tokens'] for r in active if r['config']=='default'))
initial_reduction=100*(1-sum(r['pure_initial_read_o200k_tokens'] for r in active if r['config']=='agent')/sum(r['pure_initial_read_o200k_tokens'] for r in active if r['config']=='default'))
session_reduction=100*(1-total('agent','input_tokens')/total('default','input_tokens'))
out=[]
a=out.append
a('# An opt-in Spring Boot logging profile for agent debugging\n\nAn empirical investigation, 30 September–1 October 2026. Local template application; exploratory study, not a non-inferiority trial.\n')
a('## Abstract\n')
a(f'''We implemented ten isolated Java failure fixtures in a Kotlin Spring Boot template, executed 114 final ablation measurements across eight runnable cases (three repetitions per applicable condition), and measured a revised conservative bundle in another 24 runs. Real-container cases were blocked by an unavailable Docker daemon. On full console captures, the aggressive candidate reduced summed `o200k_base` tokens by **{reduction('agent'):.1f}%**; the conservative recommendation reduced them by **{reduction('safe'):.1f}%**. These are exact counts under a named reference tokenizer, **not established Astra-specific token counts**.\n\nFresh Codex sessions actually read debugging-tool output. Sixteen sessions performed debugging, one per runnable case and condition, and produced **7/8 externally verified valid fixes in each condition**. The original 48-slot schedule exhausted account usage; 36 attempts performed no debugging and are excluded from those denominators. Four supplemental sessions covered the missing cases after reset. In the 16 active trials, reference tokens in initial complete-log reads fell {initial_reduction:.1f}%, and reference tokens in all log-related command results fell {log_reduction:.1f}%. Across the {len(paired)} matched case pairs with complete usage records, actual session input tokens fell {session_reduction:.1f}%. This small, quota-limited, sandbox-confounded sample does not establish unchanged debugging ability or a general session-token saving. Test-runner trimming erased useful source frames; it remains opt-in and is omitted from the final recommended bundle, which was measured but not directly blind-tested.\n''')
a('## 1. Questions and hypotheses\n\nRQ1: Does formatting reduce generated output, selected text, and text actually returned by debugging tools? RQ2: Do agents still identify and repair the defects? H1 predicts reduced log-related input; H2 predicts no meaningful degradation in correct fixes. We distinguish these endpoints and do not infer H2 from H1. No equivalence margin, statistical power calculation, randomized population sample, or sufficiently repeated debugging sample was available. A finding of equal successes is descriptive.\n')
a('## 2. Environment and methods\n')
a('The untouched template declared Java 25, Kotlin 2.3.21 and Spring Boot 4.1.1. It used Maven, Kotlin source directories, `spring-boot-starter`, `spring-boot-starter-test`, Kotlin JUnit integration and Logback. It had one ordinary context-loading test and no application-specific MVC, database, HTTP-client, or Testcontainers code. New experimental code is Java in `investigation/src/test/java`, added only by the Maven `investigation` profile; no language migration occurred. Dependencies added under that profile are Spring MVC, Jakarta Servlet, H2, Testcontainers PostgreSQL and PostgreSQL JDBC. The HTTP client is Spring RestClient against a JDK loopback HttpServer.\n')
a(table(['Component','Observed version/state'],[['JDK used','OpenJDK 25, macOS aarch64 (shell initially selected Temurin 17.0.13)'],['Maven / wrapper','3.9.16'],['Spring / Boot','7.0.9 / 4.1.1'],['Logback / JUnit platform','1.5.38 / 6.0.3'],['Surefire / H2 / Testcontainers','3.5.6 / 2.4.240 / 2.0.5'],['Python / tiktoken','3.9 / 0.14.0; o200k_base vocabulary'],['Codex','0.154.0-alpha.6.2; gpt-6-astra; low reasoning effort'],['Docker client','29.6.2; daemon unavailable at Docker Desktop socket'],['Git / instructions','No .git repository; no applicable AGENTS.md found; original POM and application YAML preserved']]))
a('See [environment/final.json](environment/final.json), [requirements-lock.txt](requirements-lock.txt), and the [original files](original/). Maven resolves the declared versions successfully with approved network access; no downgrade was used. Initial sandbox DNS/socket/Kotlin-daemon failures are retained under `environment/`. `DEBUG=release` in the inherited environment activated verbose Boot output in the first baseline; the measurement runner removes that variable and injected Spring/logging/JVM options consistently. Neither shared CI nor global profiles were changed. Ordinary tests pass with and without `agent`: [normal-tests.json](environment/normal-tests.json).\n')
a('### 2.1 Experimental units and resets\n\nEach matrix unit is one forked JVM executing one JUnit scenario. H2 is a fresh in-memory database, connections are closed, executors are closed, and the HTTP stub binds an ephemeral loopback port and stops in `finally`. Maven matrix runs are serial, with a 100-second process-group timeout and five-second termination grace. The runner uses already compiled sources and `surefire:test`; blind trials run the complete `test` lifecycle and therefore include compilation noise. Exact commands, statuses, identity checks, source/class hashes, and profile evidence accompany each raw run. Case 01 intentionally has no Spring context: profile activation is not applicable there; its `profile_verified=true` metadata means “no runtime profile required,” not that Spring started. Every final v2 and conservative run triggers the intended failure and returns exit 1. Repetition ranges measure formatting/runtime variability, not diagnostic population uncertainty.\n')
a('### 2.2 Provenance and producer control\n')
a(table(['Artifact/producer','What can affect it'],[['Application logger stdout','P1 prefix, P2 exception rendering; P3 only the duplicate caught-database path'],['Spring startup stdout','P1 and P2; P3 does not change Boot exception ownership'],['Surefire/Maven stdout + stderr','P4 affects Surefire failure rendering; a Spring profile does not control Maven summaries'],['Surefire XML/text reports','P4 affects report exception text; XML also embeds application output affected by P1–P3'],['Container STDOUT / STDERR','Container process; none of P1–P4 rewrites it'],['Host readiness / runtime failure','Testcontainers logger and propagated exception; P1/P2/P4 may affect host rendering, not underlying readiness reason'],['Derived extraction','Fixed parser rules only; never overwrite raw logs']]))
a('Raw stdout and stderr are separate; a “complete console” is their deterministic concatenation, not a claim of interleaved event ordering. Source paths, byte counts, line counts, SHA-256 hashes, producer labels and token counts are in [artifacts-v2.csv](artifacts-v2.csv). [The full raw-artifact inventory](raw-artifact-inventory.csv) also indexes every excluded pilot and interrupted capture. [verification.json](verification.json) checks final identities, one failing test per report, report counts, original application YAML preservation and raw hashes. Application and startup events share stdout with runner output, explicitly labeled as mixed production; they are not mislabeled as a single exception report. Generated reports are measured individually and are not silently added to console totals. Container consumers are implemented to retain host and container output separately, with container STDOUT and STDERR files; no container-output aggregate is reported because no real container ran.\n')
a('## 3. Failure cases and predefined diagnostics\n')
a(table(['Case','Mechanism and intended cause','Objective valid-fix criterion','Required initial facts'],[[c,v['name']+': '+v['cause'],v['criterion'],', '.join(v['facts'].keys())] for c,v in cases.items()]))
a('The exact fact substrings were written in [cases.json](cases.json) before the final matrix. Case 02 additionally checks that the repaired connection returns 8080; case 04 checks `port=8080`. Case 09 verifies two distinct emails after insertion. Case 07 is a discovered two-stage defect: the initial 404 is caused by `/wrong`, but changing it to `/price` exposes `UnknownContentTypeException` because an untyped numeric body has no Integer message converter. A complete repair reads the body as String and parses it. The initial checklist cannot prove preservation of information about this not-yet-triggered second failure. The first failed reference repair is preserved in [positive-controls/07.stdout](positive-controls/07.stdout); all eight complete reference repairs pass in [positive-controls-v2/results.json](positive-controls-v2/results.json). Those repairs and evaluation metadata were never copied into debugging-agent workspaces.\n')
a('Cases 09–10 use real Testcontainers objects, PostgreSQL 17.6-alpine and Alpine 3.22.1. Case 10 runs a real process announcing `worker ready` while waiting for `service ready`; the wait is eight seconds and the process lifetime is 45 seconds. Docker’s elevated probe still reported an unavailable daemon. Thus constraint/readiness failures from real containers remain **unobserved**; runtime-unavailability attempts are not counted as successful injections. [Docker blocker](environment/docker.stderr). Four actual host attempts (default and aggressive for each container case) also failed with `Could not find a valid Docker environment`; [raw attempts](raw/container-blocker/) and [metrics](artifacts-container-blocker.csv) are explicitly excluded from intended-failure and savings results. No container stdout/stderr exists because startup did not reach container creation.\n')
a('## 4. Configurations and final recommendation\n')
a('### P1–P4\n\nP1 shortens timestamps to local time with milliseconds, removes repeated PID/application-name/separator fields, eliminates padding, retains the full thread name and uses Logback logger abbreviation. P2 removes complete JUnit, Surefire and non-module-qualified Java reflection frame lines from application-logged exceptions using Logback `%replace`; it retains Spring, JDBC, HTTP and executor frames, exception headers, messages, causes, suppressed exceptions, application frames and normal common-frame elision. `%nopex` prevents Logback from appending another automatic trace. No custom converter is needed. Module-qualified Java frames do not match this narrow regex and remain.\n\nP3 applies only to case 06: the same caught SQLException was logged by two layers. The treatment retains the first full exception and both ERROR events, replacing the second trace with an explicit reference containing the same request ID. This is sole-owner logging, not a global stateful exception suppressor; messages or unrelated failures are never dropped. P4 is Maven Surefire `trimStackTrace=true`, separately enabled by `-Pagent-reports`. It cannot be enabled by a Spring profile alone.\n')
a(table(['Identifier','Enabled mechanisms'],[['default','Boot and Surefire defaults'],['p1','Prefix only; negative control in context-free case 01'],['p2','Application exception filtering only'],['p3','Sole-owner caught-database logging only'],['p4','Surefire trimming only'],['agent','Aggressive candidate: P1+P2+P3+P4; treatment in blind trials'],['safe','Final conservative bundle: P1+P2+P3, full Surefire reports; actual Spring profile is agent']]))
a('P2 is N/A for cases 01, 05, 07 and 09: their failure trace is not application-logged. P3 is N/A except case 06. The matrix runs only applicable single-mechanism conditions (plus P1 as an explicit negative control for case 01). The conservative bundle is deliberately not named a second Spring profile: the distinction is whether the separate Maven trimming option is added.\n')
a('### Exact opt-in application-agent.yml\n\n```yaml\n'+(ROOT/'src/main/resources/application-agent.yml').read_text()+'```\n')
a('The exception expression appears inline in the console pattern to avoid Spring-versus-Logback placeholder timing; the `logging.exception-conversion-word` property supplies the same policy for Boot-managed exception rendering. Normal inactive-profile logging is unchanged. Test resources `application-p1.yml` and `application-p2.yml` exist only for the experiment. Effective profiles and pattern properties are printed once per Spring fixture, and their instrumentation tokens are included in complete captures; this penalizes longer pattern settings rather than hiding their overhead.\n')
a('### Developer command\n\nSet Java 25, then use the conservative recommendation:\n\n```sh\nenv -u DEBUG mvn -Dmaven.repo.local="$PWD/investigation/.m2" -Dspring.profiles.active=agent test\n```\n\nAn ordinary developer may omit the local repository override if dependencies are in their normal Maven cache. Add `-Dkotlin.compiler.daemon=false` if working inside the restricted local sandbox. Do **not** add `-Pagent-reports` by default: P4 erased `Defects.java` locations in propagated database and HTTP failures. It remains available as an explicitly measured tradeoff. For a fully configured deliberate case, use the command in [README.md](README.md).\n')
a('## 5. Measurements and reading methods\n')
a('### 5.1 Token and agent-input definitions\n\nAll artifact token counts use real `tiktoken 0.14.0`, `o200k_base`, with special-looking text treated as ordinary text. No bytes-per-token estimate is used. `encoding_for_model("gpt-6-astra")` raises a mapping error in the installed package, so exact Astra-specific log-token attribution is **unavailable**. The reference encoding enables reproducible text comparisons. Separately, Codex `turn.completed.usage` supplies actual session input, cached input, output and reasoning-output usage when the turn completes. These counts include instructions, source reads, tool protocol and repeated context; they are not interchangeable with a tokenized file.\n\nCompleted command events contain `aggregated_output`; these returned strings are saved individually in `returned-tool-text/` and measured in [tool-results-v1.csv](tool-results-v1.csv) and [tool-results-supplemental.csv](tool-results-supplemental.csv). This captures the CLI-visible tool-result body, not the hidden model wire envelope or its overhead. Log-related results are commands reading failure logs/reports or invoking tests; mixed commands can include source/environment text, so their count is a broad observable category, not exact causal log attribution. Pure initial `cat failure.log` reads are reported separately. No output stored on disk is counted as model input merely because it exists.\n')
a('### 5.2 Fixed extraction protocol\n')
a(table(['Method','Exact rule'],[['complete','stdout followed by stderr, without truncation'],['window20','First documented failure-marker line and the next 19 raw lines'],['filtered40','First marker and next 39 raw lines, then remove frame lines matching Spring/JUnit/Apache/java/jdk/Logback packages'],['boundary','First failure event through the line before Maven’s post-test Results section'],['dedup','Same boundary; replace only byte-identical complete exception blocks with an explicit repeat reference; preserve each event header/context']]))
a('The fixed marker regex recognizes the fixture’s ERROR messages (`client setup failed`, `GET /orders`, `save users failed`, `invoice-42`, `Application run failed`) or Surefire `<<< FAILURE!` / `<<< ERROR!` lines. It ignores startup and profile-verification lines. Matching and boundary code is in [analyze.py](scripts/analyze.py); each output records match count, extraction command, source, size and fact outcomes. The rules are identical across conditions and never expanded until a desired cause appears. “20 lines after marker” is defined here to include the marker, so the policy is exactly 20 lines total. Framework filtering occurs **after** selecting 40 raw lines; filtering does not refill the window.\n\nBoundary extraction is fixture-aware, not a universal production log parser. It can retain both an application exception and the runner’s later report, intervening events and `CASE_END`; those are observed duplication/unrelated output, not additional independent failures. Exact-block dedup does not merge merely similar exceptions, different request headers or different throwables. All final extracted artifacts are no larger than their full concatenated source; the dedup reference is additional formatting, counted in its size.\n')
a('### 5.3 Per-case full console results\n\nMean [minimum–maximum] over three repetitions. Counts include Maven overhead and explicit profile evidence. “Safe” is the recommended untrimmed-report configuration.\n')
a(table(['Case','Default bytes','Safe bytes','Default tokens','Aggressive tokens','Safe tokens','Safe change'],[[c,form(group(c,'default'),'bytes'),form(group(c,'safe'),'bytes'),form(group(c,'default')),form(group(c,'agent')),form(group(c,'safe')),f"{100*(1-mean(group(c,'safe'))/mean(group(c,'default'))):.1f}% reduction"] for c in list(cases)[:8]]))
a('Cases 09–10: unavailable; no zero values or simulated savings are substituted. [All extraction results, CSV](results-v2.csv), [JSON](results-v2.json), [conservative CSV](results-conservative-v2.csv).\n\n![Per-case token reduction](plots/token-reduction.png)\n')
a('### 5.4 Ablations\n\nMean complete-console reference tokens; dash means not applicable.\n')
a(table(['Case','Default','P1','P2','P3','P4','Aggressive','Safe'],[[c]+[f'{mean(group(c,cfg)):,.1f}' if group(c,cfg) else '—' for cfg in ['default','p1','p2','p3','p4','agent','safe']] for c in list(cases)[:8]]))
a('P1 alone barely changes the context-free assertion, because Spring formatting cannot affect it. P2 alone increases async complete-console size: it removes few worker frames while the effective-configuration line adds the regex. This is a real unfavorable measurement, not omitted noise. P3 is particularly effective for the duplicated caught database trace. The conservative bundle increases complete-console counts for cases 01, 05, 07 and 08: the preserved runner report and printed effective-pattern instrumentation can outweigh prefix savings. These observations show why file-wide or pooled savings cannot be applied universally.\n')
a('### 5.5 Extraction and diagnostic survival\n\nEach cell reports reference-token mean followed by required facts retained/required in repetition 1. Full machine-readable per-run fact maps are in the result files.\n')
a(table(['Case / configuration','Complete','20 lines','Filtered 40','Boundary','Dedup'],[[c+' / '+cfg]+[f"{mean(group(c,cfg,m)):,.1f}; {group(c,cfg,m)[0]['facts_present']}/{group(c,cfg,m)[0]['facts_required']}" for m in ['complete','window20','filtered40','boundary','dedup']] for c in list(cases)[:8] for cfg in ['default','agent','safe']]))
a('Substring survival is a necessary-content proxy, not proof of comprehension. It does not establish semantic completeness, readable causal ordering, or a successful repair. Default async output truncates `invoice-worker-7`; the agent pattern retains it, so default fails the strict full-thread-name fact although its suffix and request ID still help. Conversely, P4 removes application source frames in cases 05 and 07 even from the complete console. The conservative bundle restores them. In case 02, both fixed default windows miss the nested causes and suppressed cleanup exception because framework frames consume the window; filtering after the window cannot recover unseen lines. Context startup similarly exceeds fixed windows. Removing Spring frames from filtered windows can also erase useful lifecycle context even when a broad substring fact survives. No window is silently enlarged.\n')
a(f'The pooled full-console reduction is {reduction("agent"):.1f}% for the aggressive candidate and {reduction("safe"):.1f}% for the recommendation, computed as `1 − sum(treatment tokens)/sum(default tokens)` across eight cases × three repetitions. Every case has equal repetition count, but long traces carry more weight. No container cases are included; this is not an average percentage across projects, reading methods or sessions.\n')
a('## 6. Direct debugging trials\n\nEach trial used a new external temporary project with the same defective implementation for its case, model `gpt-6-astra`, low reasoning effort and a 120-second wall-time cap. No conversation was resumed. The workspace included source/tests and a complete failing console log, but no case manifest, reference fixes, earlier logs, report, transcripts or outcome metadata. The prompt asked the model to read `failure.log`, make the smallest behavioral repair in `Defects.java` only, and verify with `./test.sh`; it prohibited disabling functionality or changing expectations. Full stdout/stderr remained available. Immutable files were checked and restored before an independent external test run. All active trial patches and diagnoses were reviewed; no test expectation changes or functionality-disabling patches were observed.\n\nThe shared dependency cache and installed tools were allowed; other outside reads were prohibited by instructions. This is protocol isolation rather than a sealed adversarial evaluation. Parallel independent copies avoid source and report collisions, but CPU contention and cache state may affect time. The original schedule alternated condition order by repetition. Quota prevented repetitions 2–3 from doing work. Twelve original sessions produced patches (one was interrupted by quota after its patch); four supplemental sessions completed the HTTP/async pairs after reset. Pilot trials are retained but excluded from primary outcomes because they preceded final fixture/profile instrumentation. **There is one active trial per case and condition, not three.**\n')
a(table(['Case','Default valid fix','Agent valid fix','Default seconds to external verification','Agent seconds','Root cause'],[[c]+[('1/1' if next(r for r in active if r['case']==c and r['config']==cfg)['fix_valid'] else '0/1') for cfg in ['default','agent']]+[f"{next(r for r in active if r['case']==c and r['config']==cfg)['time_to_external_verification_seconds']:.1f}" if next(r for r in active if r['case']==c and r['config']==cfg)['fix_valid'] else 'unresolved' for cfg in ['default','agent']]+['Initial cause correct in both; HTTP second failure unresolved' if c=='07' else 'Correct in both'] for c in list(cases)[:8]]))
a('![Observed debugging outcomes](plots/debugging-outcomes.png)\n\nBoth HTTP agents changed only the route and stopped without resolving the second failure. External verification returned 1 with `UnknownContentTypeException`; these are incomplete, not valid or superficial test-bypassing fixes. The other seven repairs in each condition are narrowly targeted and pass. Async patches preserve the executor and exception propagation. The quota-interrupted database default patch is externally valid but has no completed session usage record. Model-declared verification is not treated as authoritative: some agents reported being blocked by Kotlin daemon filesystem/socket restrictions, while external verification could run. This environmental friction limits conclusions about autonomous time-to-fix. The displayed successful time sums session wall time and external verification; it excludes initial setup, and is an upper bound on patch discovery time, not a measured first-success timestamp inside the session.\n')
a('### 6.1 Returned text, tool calls and actual usage\n')
a(table(['Case / condition','Log-related calls','Pure initial-read reference tokens','All log-related reference tokens','Input tokens','Cached input','Output tokens'],[[r['case']+' / '+r['config'],r['log_related_tool_calls'],r['pure_initial_read_o200k_tokens'],r['log_related_o200k_tokens'],r['input_tokens'] if r['input_tokens'] is not None else 'unavailable',r['cached_input_tokens'] if r['cached_input_tokens'] is not None else 'unavailable',r['output_tokens'] if r['output_tokens'] is not None else 'unavailable'] for r in sorted(active,key=lambda r:(r['case'],r['config']))]))
a(f'''Across 16 active sessions, pure initial returned-log reads shrink by {initial_reduction:.1f}% under the reference encoding; all log-related command result bodies shrink by {log_reduction:.1f}%. Fuller-output requests matching the documented original-stream/report rule: {sum(r['fuller_output_requests'] for r in active)}. This does not mean no repeated reading: reruns and source/environment inspection are included in the transcripts. Returned output may be tool-truncated; detected truncation markers across completed command results: {sum(r['truncated_tool_results'] for r in active)}. These markers are a string-based indicator, not proof that every unmarked result was untruncated. Raw files remain complete.\n\nFor actual session usage, compare only matched cases {', '.join(paired)}; case 06 is excluded because its default session was quota-interrupted. Summed default/agent input tokens are **{total('default','input_tokens'):,} / {total('agent','input_tokens'):,}**, a descriptive {session_reduction:.1f}% decrease. Cached input is **{total('default','cached_input_tokens'):,} / {total('agent','cached_input_tokens'):,}** and output tokens are **{total('default','output_tokens'):,} / {total('agent','output_tokens'):,}**. Individual sessions include both increases and decreases. Cache state, differing tool retries, large fixed instructions, read repetition and sandbox failures dominate some sessions. No claim that the log profile caused this exact total-session difference is justified. Do not sum cached input on top of input, or add separately reported reasoning tokens to output without knowing the provider’s accounting semantics.\n''')
a('Transcripts, patches, diagnoses and verification are under [trials/v1](trials/v1/) and [trials/supplemental](trials/supplemental/); summaries are [trial-results-v1.csv](trial-results-v1.csv) and [supplemental CSV](trial-results-supplemental.csv). Empty/no-patch quota attempts are distinguishable in each `outcome.json` and are not unresolved debugging attempts. The runner now stops scheduling work after a quota error. The conservative revised bundle was **not** the treatment in these trials: its application profile is identical, but P4 is omitted. Its debugging performance remains directly unmeasured.\n')
a('## 7. Interpretation, tradeoffs and financial implications\n\nThe strongest supported finding is that the captured/generated text and the returned initial tool-result bodies can be smaller. These are distinct from total model input and successful diagnosis. Narrow exception filtering produces the main reduction for application-logged failures. Keeping all Spring/JDBC/HTTP frames is important because startup, SQL and HTTP diagnoses can rely on those frameworks. The parser still removes JUnit/reflection details that would matter if the test engine or reflection itself were broken; use default logs for such investigations. The experiment deliberately does not suppress ERROR, lower log levels or truncate at an arbitrary byte limit.\n\nShort timestamps lose date/time-zone context across midnight; removing PID and constant application name assumes a single captured process/application. Logger abbreviation can collide; full thread names may be long but were useful here. The tested pattern does not explicitly include arbitrary MDC or tracing correlation fields; request context in these fixtures is in the message. It is unsuitable as a drop-in assumption for every distributed tracing setup without extension and re-evaluation. P3 cannot be generalized from identical caught objects to unrelated exceptions with equal messages. P4’s information loss is why the final recommendation retains full runner reports.\n\nNo current price schedule is assumed. Given explicitly supplied prices per million uncached input, cached input and output tokens, compute cost as `((I−C)×p_uncached + C×p_cached + O×p_output)/1e6`, then compare sessions with complete usage. Repeated reads and caching can make equal log-token reductions yield different monetary changes. A byte reduction or reference-encoding count alone is not a dollar saving.\n')
a('## 8. Limitations and threats to validity\n\n- Eight runnable toy failures in one template, with two real-container cases blocked; no generalization to production outages or multilingual stacks.\n- One active blind trial per case/condition, resource-limited and partly resumed after a calendar/account reset; no equivalence claim or statistical non-inferiority conclusion.\n- Account quota and sandbox verification restrictions confound time and usage. A valid externally verified patch is not necessarily a completed autonomous repair session.\n- The final conservative bundle was selected after observing source-frame loss on these same cases and was not separately blind-tested; adaptive selection and no holdout set limit validation.\n- Exact model-specific log-token attribution is unavailable; reference-tokenizer results and actual whole-session usage must remain separate. CLI tool bodies omit hidden protocol overhead.\n- Diagnostic facts are substring checks. The HTTP second failure demonstrates their incompleteness. Supplied tests are small; manual patch review reduces but cannot eliminate test-overfitting risk.\n- The preliminary pilots include harness/configuration mistakes and an interrupted conservative batch. They are preserved, excluded from final pooled results, and documented in [amendments.json](amendments.json).\n- V1 P2-only settings were ineffective; v2 corrects them. Initial concurrent pilot reports were not reliably isolated, so no claims rely on their report completeness. The final v2 and conservative-v2 raw reports are isolated.\n- Live source instrumentation changed between pilot/final runs; only designated final batches are pooled. Main behavioral defects stayed fixed during final comparisons; debug-only container log-capture additions do not alter non-container behavior.\n')
a('## 9. Conclusions\n\nThe opt-in profile demonstrably reduces captured and selected log text for these cases under a documented reference tokenizer, and actual debugging sessions received smaller initial log-result bodies. Actual total-session input also differed in the matched observed sessions, but causality and general savings are not established. Observed valid-fix counts were equal at 7/8 per condition; both conditions failed to complete the two-stage HTTP repair. This supports continued evaluation, **not** the assertion that debugging ability is unaffected. Real-container behavior, repeated blind trials and direct testing of the final conservative bundle remain outstanding. The recommended practical configuration is the Spring `agent` profile with full Surefire reports.\n')
a('## Appendix A. Commands and exact configurations\n\nAll reproduction commands, prerequisites and clean-state rules are in [README.md](README.md). The authoritative per-run commands are in `raw/*/*/*/*/metadata.json`; the authoritative trial invocation and budget are in `trials/*/*/*/*/outcome.json`. Primary runs:\n\n```sh\npython3 investigation/scripts/run.py --batch v2 --workers 1\npython3 investigation/scripts/run.py --batch conservative-v2 --configs safe --workers 1\ninvestigation/.venv/bin/python investigation/scripts/analyze.py --batch v2\ninvestigation/.venv/bin/python investigation/scripts/analyze.py --batch conservative-v2\npython3 investigation/scripts/trials.py --batch v1 --repeats 3 --workers 2 --seconds 120\npython3 investigation/scripts/trials.py --cases 07,08 --repeats 1 --batch supplemental --workers 2 --seconds 120\n```\n\nThese batch names already exist and are protected against overwrite; use fresh names for reproduction. Compile the `investigation` Maven profile first. Ordinary Maven builds must not overlap matrix execution because they can remove experimental classes.\n')
a('## Appendix B. Representative unmodified excerpts\n\nExcerpts below are bounded illustrations, not the inputs used to compute full-log metrics. Complete sources are linked.\n')
for cfg,label in [('default','Before'),('safe','After (recommended)')]:
 batch='v2' if cfg=='default' else 'conservative-v2'
 path=D/f'raw/{batch}/02/{cfg}/1/stdout.log';lines=path.read_text().splitlines();start=next(i for i,l in enumerate(lines) if 'client setup failed' in l)
 a(f'### {label}: nested exception\n\n[Complete raw stdout](raw/{batch}/02/{cfg}/1/stdout.log)\n\n```text\n'+'\n'.join(lines[start:start+26])+'\n```\n')
for case in ['05','08']:
 a(f'Case {case}: [default full console](extracted/v2/{case}/default/1/complete.txt), [aggressive full console](extracted/v2/{case}/agent/1/complete.txt), [conservative full console](extracted/conservative-v2/{case}/safe/1/complete.txt). These show the runner-frame loss and full-thread-name preservation respectively.\n')
a('## Appendix C. Primary documentation\n\nThe implementation was checked against [Spring Boot logging](https://docs.spring.io/spring-boot/reference/features/logging.html), [Logback pattern layouts](https://logback.qos.ch/manual/layouts.html), [Surefire test parameters](https://maven.apache.org/surefire/maven-surefire-plugin/test-mojo.html), and [OpenAI non-interactive Codex documentation](https://learn.chatgpt.com/docs/non-interactive-mode). Local CLI help and actual runtime behavior determine the commands recorded here. Official OpenAI documentation was consulted using the [OpenAI Docs skill](/Users/hadiranjbar/.codex/skills/.system/openai-docs/SKILL.md). No external person was messaged.\n')
(D/'REPORT.full-read.md').write_text('\n'.join(out))
# Figures: static, exportable, clearly scoped to the measured reference encoding.
os.environ.setdefault('MPLCONFIGDIR',str(D/'.mpl'))
import matplotlib;matplotlib.use('Agg')
import matplotlib.pyplot as plt
import numpy as np
(D/'plots').mkdir(exist_ok=True)
x=np.arange(8);fig,ax=plt.subplots(figsize=(11,5))
for offset,cfg,label in [(-.18,'agent','Aggressive candidate (+ P4)'),(.18,'safe','Recommendation (full runner report)')]:
 values=[100*(1-mean(group(c,cfg))/mean(group(c,'default'))) for c in list(cases)[:8]]
 ax.bar(x+offset,values,.36,label=label)
ax.set_xticks(x,[c+'\n'+'\n'.join(textwrap.wrap(cases[c]['name'],14)) for c in list(cases)[:8]],fontsize=8);ax.set_ylabel('Reduction in full-console o200k_base tokens (%)');ax.set_title('Three captures per condition; containers unavailable');ax.axhline(0,color='black',linewidth=.6);ax.legend(fontsize=8);fig.tight_layout();fig.savefig(D/'plots/token-reduction.png',dpi=180);fig.savefig(D/'plots/token-reduction.svg');plt.close(fig)
fig,ax=plt.subplots(figsize=(9,3.5))
for offset,cfg,label in [(-.15,'default','Default'),(.15,'agent','Aggressive agent')]:
 vals=[int(next(r for r in active if r['case']==c and r['config']==cfg)['fix_valid']) for c in list(cases)[:8]]
 ax.scatter(x+offset,vals,label=label,s=85)
ax.set_xticks(x,list(cases)[:8]);ax.set_yticks([0,1],['Incomplete repair','Externally verified valid fix']);ax.set_ylim(-.25,1.25);ax.set_xlabel('Case (one active independent trial per condition)');ax.set_title('7/8 valid fixes in each condition; not evidence of equivalence');ax.legend();fig.tight_layout();fig.savefig(D/'plots/debugging-outcomes.png',dpi=180);fig.savefig(D/'plots/debugging-outcomes.svg');plt.close(fig)
print('Legacy REPORT.full-read.md and legacy figures generated; natural report is untouched')
