#!/usr/bin/env python3
"""Keep new routine findings separate from the preserved failure-only investigation."""
import collections,json,statistics
from analyze import ROOT
from routine_trials import PASS_PROMPT,MIXED_PROMPT,SCENARIOS
D=ROOT/'investigation';B=D/'routine-reading/main'
def table(headers,rows):
 return '| '+' | '.join(headers)+' |\n| '+' | '.join(['---']*len(headers))+' |\n'+''.join('| '+' | '.join(str(v).replace('|','\\|').replace('\n',' ') for v in r)+' |\n' for r in rows)+'\n'
def generate():
 rows=json.loads((B/'trial-results.json').read_text());secondary=json.loads((B/'secondary-results.json').read_text());tools=json.loads((B/'tool-results.json').read_text())
 active=[r for r in rows if r['debugging_began']];parts=[];a=parts.append
 a('# Everyday verification, mixed-suite debugging, and failure diagnosis\n')
 a('This revision adds five passing-operation scenarios and a mostly passing suite with one failure. **Normal-operation volume, observed agent behavior, and failure diagnosis are separate results.** The previous failure-only report is preserved [here](REPORT.failure-only.md); its raw data and tables are unchanged. Its 49.3% non-container and 37.2% container reductions cannot be generalized to everyday verification.\n')
 a('## New study status and primary findings\n')
 a(table(['Agent state','Planned slots'],sorted(collections.Counter(r['status'] for r in rows).items())))
 a(f'The schedule plans three independent trials per scenario and logging condition (36 slots), prioritizing the live mixed suite. **{len(active)} sessions performed agent work.** Setup/data-collection runs below are not agent trials. Never-begun slots do not count as debugging failures or zero-consumption successes. [Schedule and exact settings](routine-reading/main/schedule.json).\n')
 a('**Capture qualification:** retained `command_execution.aggregated_output` bodies are measurable, but they are not established as complete model-visible tool responses. Some `cat AGENTS.md; ./test.sh` records contain only Maven output and omit the expected initial instructions. The cause is not established. [Concrete capture audit](routine-reading/main/capture-audit.json). Counts below are **retained-event text**, with attribution bounds inside those bodies; they are partial command-output evidence, not guaranteed bounds on complete model-visible consumption. Omitted chunks and possible tool-level truncation cannot be recovered from these events alone. No missing text is filled in from files. Thus percentage differences in retained events do not establish total consumed-output savings. Historical CLI-body figures below should likewise be read as retained text, not independently proven complete model-input totals. Exact full-file matches establish the retained body; they do not resolve hidden protocol/chunk behavior. Raw historical evidence remains unchanged.\n')
 if not active:
  a('**No new agent-reading or outcome comparison is available.** The first launch was prevented by the recorded resource error, and the runner did not schedule further sessions after quota. Consequently, success recognition, warning recognition, diagnosis, actual log consumption and provider usage are unobserved in this addition. A smaller stored log is not evidence that an agent read less. The completed measurements below establish only available output volume and preserved event content.\n')
 else:
  a(table(['Scenario / arm / repeat','Inspection tokens lower–upper','Test-command tokens','Source tokens','Mixed tokens','Implementation valid','Success assessment','Warning recognized'],[[f"{r['scenario']} / {r['condition']} / {r['run']}",f"{r['log_tokens_lower']}–{r['log_tokens_upper']}",r['test_command_tokens'],r['source_read_tokens'],r['mixed_tokens'],r['fix_valid'],r['success_recognized'],r['warning_recognized']] for r in active]))
  a('Matched comparisons below retain only case/repetition pairs in which both sessions actually began. Output classes remain separate. No complete-file count is substituted for consumed text.\n')
  paired_data=[]
  for scenario in SCENARIOS:
   pairs=[]
   for run in [1,2,3]:
    pair=[next((r for r in active if r['scenario']==scenario and r['condition']==c and r['run']==run),None) for c in ['default','conservative']]
    if all(pair):pairs.append(pair)
   if pairs:
    totals=[[sum(p[i][k] for p in pairs) for k in ['log_tokens_lower','log_tokens_upper','test_command_tokens','mixed_tokens']] for i in [0,1]]
    paired_data.append([scenario,len(pairs),f"{totals[0][0]}–{totals[0][1]} / {totals[1][0]}–{totals[1][1]}",f"{totals[0][2]} / {totals[1][2]}",f"{totals[0][3]} / {totals[1][3]}"])
  a(table(['Scenario','Matched pairs','Inspection tokens D / C','Test-command tokens D / C','Whole mixed tokens D / C'],paired_data))
  comparison=[]
  for scenario in SCENARIOS:
   matched=[]
   for run in [1,2,3]:
    pair=[next((r for r in active if r['scenario']==scenario and r['condition']==c and r['run']==run),None) for c in ['default','conservative']]
    if all(pair):matched.append(pair)
   if not matched:continue
   lo=[sum(p[i]['verification_output_tokens_lower'] for p in matched) for i in [0,1]]
   hi=[sum(p[i]['verification_output_tokens_upper'] for p in matched) for i in [0,1]]
   change=f"{100*(lo[1]/lo[0]-1):+.1f}%" if lo==hi and lo[0] else 'bounded; see totals'
   comparison.append([scenario,len(matched),f"{lo[0]:,}–{hi[0]:,}",f"{lo[1]:,}–{hi[1]:,}",change,' / '.join(str(sum(p[i].get('agent_rerun_success') is True for p in matched)) for i in [0,1])])
  a('Combined **inspection plus returned test output** is the intended new workflow endpoint for this addition, distinct from the old log-only endpoint. Pure test results are counted once; attributable mixed log segments count once; unresolved mixed test/source text broadens bounds to the whole body. Source-only/discovery text is excluded and remains separately reported. The retained-event version prevents a live test run from being mistaken for zero output, but missing emitted chunks still prevent a complete consumption claim.\n')
  a(table(['Scenario','Pairs','Default retained combined tokens','Conservative retained combined tokens','Retained change','Successful agent reruns D / C'],comparison))
  a(table(['Scenario / arm','Log calls','Searches','Context requests','Full-file requests','Exact repeats','Test commands'],[[s+' / '+c]+[sum(r[k] for r in active if r['scenario']==s and r['condition']==c) for k in ['log_calls','search_calls','context_requests','full_file_requests','repeated_commands','test_commands']] for s in SCENARIOS for c in ['default','conservative'] if any(r['scenario']==s and r['condition']==c for r in active)]))
  a('The live mixed-suite result is especially sensitive to reruns: an agent can read a smaller formatted run yet consume more cumulative output by performing additional verification. Interpretation must include both inspection and test-command columns, and any unresolved mixed attribution. Do not add the whole mixed column to attributed log segments a second time.\n')
  a('Implementation validity is independently checked against original tests; it does not imply that an agent completed a successful rerun. Per-trial `agent_rerun_success` and reviews distinguish successful verification from accurate reports of a previous pass followed by a sandbox-blocked attempt. HTTP/container attempts with environment-generated exceptions are not evidence of ordinary successful-operation savings; inspect them separately.\n')
  a('These counts describe the returned strings retained in completed command events. Mixed full bodies overlap attributed segments and are not additive. A zero file-inspection count does not imply zero output consumed: live test-command output is a separate endpoint, particularly for the mixed suite. [Complete per-trial and usage table](routine-reading/main/trial-results.csv), [commands and returned strings](routine-reading/main/tool-results.json). Manual outcomes are separate from raw sessions.\n')
 a('### Outcome interpretation for this collection\n\nTwenty sessions completed and one database session was quota-interrupted after inspection; fifteen slots were never scheduled. All four completed mixed-suite sessions (two per arm) located the sole failure, made only the multiplication repair, and passed all thirteen original tests. Ten completed passing-verification sessions (unit, integration, database) successfully reran their selected tests and correctly reported success. Six HTTP/container sessions correctly distinguished a prior pass from sandbox-blocked live verification; they are not fully successful normal-operation reruns. The interrupted session has no recorded success or warning assessment.\n\nAll twenty completed sessions reported the relevant warning(s), including JVM deprecation warnings where there was no application warning. Container default repetition 1 actually read combined and stderr streams, consuming the same warning twice; conservative repetition 1 identified the warning from source inspection and did not read those stream files. Correct recognition therefore does not establish a common reading strategy. The stale-cache message is authored by the fixture and does not implement or prove real fallback behavior. There is no evidence of equivalence from this small sample.\n')
 a('## Design: passing verification and live failure discovery\n')
 a(table(['Scenario','What runs','Evaluation'],[
 ['Passing unit','Two arithmetic checks, no Spring startup/log events','Recognize success without application-log evidence; measure any overhead.'],
 ['Passing integration','Real Spring context, bean and refresh; INFO plus WARN','Recognize pass while noticing the nonfatal stale-cache warning and fallback.'],
 ['Successful HTTP request','Real loopback JDK HTTP server and client; GET /price','Retain method/path/status/request ID; assert 200, body 30 and correlation header.'],
 ['Successful database operation','Two real H2 inserts under a unique constraint','Retain both rows and request/operation/table/count without exceptions.'],
 ['Successful container test','Real Alpine readiness, stdout and stderr','Separate host formatting from container-origin text and retain a stderr warning.'],
 ['Mostly passing suite','Twelve passing record checks, one failing price assertion','Locate the failure, repair implementation, rerun all thirteen; do not ignore a coexisting warning.']]))
 a('Passing tasks receive an already-applied, correct implementation change as `change.diff` and complete previous `test-output.log`. They may rerun tests or inspect any available evidence. Mixed tasks receive **no prepared log or test report**: the agent must start by executing the suite. The initial 12/13 outcome is known only to the evaluator, not stated in the prompt. Source, tests, implementation scope and budgets are identical across logging conditions within each scenario.\n\nPassing prompt:\n\n> '+PASS_PROMPT+'\n\nMixed-suite prompt:\n\n> '+MIXED_PROMPT+'\n')
 a('The profile is the unchanged conservative Spring `agent` profile, with full Surefire (`-DtrimStackTrace=false`); no aggressive trimming. Separate activation/encoder probes run before initial measurement and before each launched trial. The model is `gpt-6-astra`, low reasoning effort, fresh ephemeral workspace-write sessions with a 120-second budget. Condition order alternates; agent sessions are sequential to avoid shared temporary-file interference. Initial collection can use two workers. This concurrency change and different fixtures preclude causal comparisons across cohorts.\n')
 a('The same neutral workspace instructions identify `./test.sh` and `RoutineService.java` and preserve tests/configuration. Mixed repairs are independently verified in pristine copies with all thirteen original tests; expected counts cannot be changed. Passing judgments separately score correct recognition of success and reported warnings. No passing exit code or log read alone proves either recognition. Docker and loopback sandbox restrictions may affect agent verification; outer-evaluator successes must never be described as agent-side successes. [Full protocol and criteria](routine-reading/PROTOCOL.md).\n')
 a('## Secondary normal-operation output volumes\n\nThe following are **complete stored console captures**, not agent consumption. Means use three independent captures per condition. They include Maven, JVM startup/compile warnings, full Surefire and application text; setup profile probes are excluded. The unit fixture emits no application logs but still has build/JVM output.\n')
 data=[]
 for s in ['unit','integration','http','database','container','mixed']:
  groups={c:[r for r in secondary if r['scenario']==s and r['condition']==c and r['valid']] for c in ['default','conservative']}
  vals={c:statistics.mean(r['tokens'] for r in g) if g else None for c,g in groups.items()}
  change=f"{100*(vals['conservative']/vals['default']-1):+.1f}%" if all(vals.values()) else 'unavailable'
  data.append([s,' / '.join(str(len(groups[c])) for c in groups),*(f"{vals[c]:,.1f}" if vals[c] is not None else 'unavailable' for c in groups),change])
 a(table(['Scenario','n default / conservative','Default tokens mean','Conservative tokens mean','Change'],data))
 a('Reference tokenizer: tiktoken `o200k_base`; exact Astra attribution is not claimed. Random paths, timestamps, run duration and lifecycle messages can change counts slightly even when formatting is irrelevant. Small unit-test differences must not be interpreted as a profile effect. Mixed-suite figures are initial failing-run volumes, **not normal-operation savings** and not evidence of efficient agent failure discovery. [All counts, bytes, signals and raw paths](routine-reading/main/secondary-results.json).\n')
 a('## Warning and request-context retention\n')
 a(table(['Scenario','Expected application signals','Signals retained in all valid captures'],[[s,'; '.join(next((r['signals'].keys() for r in secondary if r['scenario']==s),[])) or 'No application events',all(all(r['signals'].values()) for r in secondary if r['scenario']==s and r['valid'])] for s in SCENARIOS]))
 a('The integration/mixed warning is a controlled `inventory cache stale` event containing request ID, age, threshold and database fallback. HTTP retains method, path, status and request correlation; database retains operation, table, row count and status. The fixture does not exercise production servlet access logging, distributed tracing, high-volume concurrency, or long-running operation after startup. Retention means text remains available; it does **not** mean an agent noticed or correctly interpreted it.\n')
 container=[r for r in secondary if r['scenario']=='container' and r['valid']]
 a('Container stdout (`worker ready`) and stderr (`WARN cache stale request=worker-7 age=61s threshold=60s`) are retained as actual Docker stream files. Those raw streams are separate from host Spring/Testcontainers logging. The combined `.container.log` is an alternate copy, not extra producer volume. [Stream counts and hashes](routine-reading/main/verification.json). The Spring formatter cannot shorten raw container streams; host-prefix savings must not be advertised as container-output compression.\n')
 a('Representative passing output (message payloads preserved under both profiles):\n\n```text\nrefresh completed request=refresh-7 records=12 status=ok\ninventory cache stale request=refresh-7 age=61s threshold=60s fallback=database\nrequest=http-7 method=GET path=/price status=200 total=30\nrequest=db-7 operation=insert table=users rows=2 status=committed\n```\n\nThese excerpts omit prefixes for presentation. Full returned/produced strings remain in raw artifacts. [Integration default](routine-reading/main/initial/integration/default/1/test-output.log), [integration conservative](routine-reading/main/initial/integration/conservative/1/test-output.log), [container streams](routine-reading/main/initial/container/conservative/1/initial-container-logs/).\n')
 a('## Commands, independent verification, and actual usage\n')
 a('Initial checks retain exact Maven commands, exit status, test counts and profile artifacts in each `result.json`. All mixed initial runs must have 13 tests, exactly one assertion failure, no errors/skips; [reference controls](routine-reading/main/controls/) independently confirm the multiplication repair passes all thirteen under both conditions. The ordinary application test suite passed after these additions; [command/result](routine-reading/ordinary-suite.json). The 13 existing classifier checks and 5 new routine-measurement checks also passed. Ordinary application tests remain separate. Setup measurements are not successful autonomous repairs.\n')
 if active:
  a(table(['Scenario / arm / repeat','Input','Cached input','Output','Seconds session / verifier'],[[f"{r['scenario']} / {r['condition']} / {r['run']}",r['input_tokens'],r['cached_input_tokens'],r['output_tokens'],f"{r['elapsed_seconds']} / {r['verification_seconds']}"] for r in active]))
  examples=[]
  for scenario in SCENARIOS:
   for cond in ['default','conservative']:
    candidate=next((t for t in tools if t['scenario']==scenario and t['condition']==cond and (t['log_directed'] or t['test_execution'])),None)
    if candidate:examples.append(candidate)
  for t in examples:
   p=ROOT/t['returned_text'];a(f"Recorded command ({t['scenario']}, {t['condition']}, repetition {t['run']}):\n\n```sh\n{t['command']}\n```\n\n[Returned body]({p.relative_to(D)})\n\n```text\n"+"\n".join(p.read_text().splitlines()[-10:])+"\n```\n")
 else:
  first=next((r for r in rows if r['status']!='not_scheduled_quota'),None)
  if first:a(f"[Attempted launch and outcome]({first['evidence'].removeprefix('investigation/')}/outcome.json), [raw session]({first['evidence'].removeprefix('investigation/')}/session.jsonl). No completed inspection commands or provider usage were available; no representative reading excerpt is fabricated.\n")
 a('Provider input/cached input/output, when available, are whole-session values and are never substituted for reference-tokenized returned text. Source reads, reasoning, repeated context, tool framing, cache state and test execution all affect them. Unknown usage stays unavailable.\n')
 a('The confirmatory mixed-suite batch intended to retain model-visible tool-response chunks **never started**: automatic approval review rejected its preparation/launch because the reviewer hit its usage limit. This is distinct from the already-running batch’s model quota interruption. No confirmatory commands, repairs or token counts are claimed. [Exact disposition](routine-reading/confirmatory-status.json).\n')
 a('## Interpretation and limitations\n\nPassing-operation savings must be assessed on their own. Exception-heavy failure reductions cannot establish everyday benefit; pure unit tests offer no application-prefix savings, raw container streams remain separate, and live test output can dominate actual consumption. Preserving known message payloads demonstrates that these controlled warnings/context are not filtered out, but does not prove preservation of every diagnostic signal or agent recognition.\n\nThe mostly passing suite is a more realistic discovery task than a supplied failure log, but remains a small synthetic suite with an identified implementation file and only one defect. No equivalence or non-inferiority claim is supported by these sample sizes. **Conclusion:** the conservative profile reduced complete available passing logs by roughly 7–9% for integration/HTTP/database and 20% for host/container-test console output, with effectively no unit-test reduction. Known warning/request payloads and raw container streams remained available. Agents demonstrated correct mixed-suite repair and warning awareness in the observed sample, but the capture gap prevents a complete cumulative-consumption claim; sandbox-blocked verification must remain separate. The active-trial outcomes and capture limitations, not file-volume percentages, determine which aspects of the central question have actually been observed. Missing scenarios/repetitions and unrecorded explanations remain unobserved. Extra reruns can offset shorter formatting; there is no general everyday-workflow saving without evidence from both inspections and live test output.\n')
 a('## Reproduction and evidence\n\nOfficial documentation describes `--json` as an emitted event stream and `--ephemeral` as disabling rollout persistence; it does not establish full model-visible chunk capture for this installed build. [OpenAI non-interactive mode documentation](https://learn.chatgpt.com/docs/non-interactive-mode). A future confirmatory cohort should retain/audit raw model-visible tool-response chunks before claiming complete consumed-output totals.\n\n```sh\npython3 investigation/scripts/routine_trials.py --batch NEW_BATCH --mode collect\npython3 investigation/scripts/routine_trials.py --batch NEW_BATCH --mode trials\n```\n\nThe harness refuses existing raw slots and stops scheduling on quota. Analyzer/report scripts explicitly select the recorded `main` cohort. Do not restart the same schedule over existing sessions; use a new batch after resources are available. [Protocol](routine-reading/PROTOCOL.md), [source fixtures](src/test/java/com/ai/token/experiment/RoutineCasesTest.java), [trial outcomes](routine-reading/main/trial-results.json), [raw integrity checks](routine-reading/main/verification.json), [preserved historical hashes](routine-reading/preserved-sha256.json).\n')
 a('## Earlier failure diagnosis: separate cohorts\n\nThe complete [failure-only investigation](REPORT.failure-only.md), [earlier natural-reading report](REPORT.natural-pre-containers.md), and [forced-full-read baseline](REPORT.full-read.md) remain preserved. Their task prompts, per-case findings, commands, returned excerpts, fixes and limitations are available there; no old raw artifacts or result tables were regenerated.\n')
 a(table(['Earlier cohort','Active trials','Verified repairs default / treatment','Retained-log comparison'],[
 ['Forced-first-full-read baseline','16','7/8 / 7/8','Different prompt and aggressive Surefire treatment; not pooled.'],
 ['Natural reading, cases 01–08','22','8/11 / 8/11','49.3% less identifiable retained log text across 11 matched pairs.'],
 ['Natural reading, Docker cases 09–10','9','4/5 / 4/4','37.2% less across 4 matched completed pairs; one unpaired quota interruption.']]))
 a('These remain failure-diagnosis findings, not evidence about passing work. The historical natural-reading primary endpoint counted retained inspection bodies, while this addition also examines live test output. The newly documented event-capture limitation prevents treating any command-body tally as an independently established complete model-input total. The earlier [raw natural-reading ledger](natural-reading/main/tool-results.json), [Docker ledger](natural-reading/containers/tool-results.json), and [baseline integrity manifest](baselines/full-read/preserved-sha256.json) remain unchanged.\n')
 (D/'REPORT.md').write_text('\n'.join(parts))
if __name__=='__main__':generate()
